name: Android Build (Release + Debug)

on:
  workflow_dispatch:
  push:
   branches: [ main ]
   
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      # -------- Debug APK --------
      - name: Build debug APK
        run: flutter build apk --debug --dart-define=APP_PACKAGE_ID=de.meinterminplaner.app

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: mein-terminplaner-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      # -------- Release (signed) --------
      - name: Decode keystore
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
         mkdir -p android/app
         echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore

      - name: Create key.properties
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          cat > android/key.properties << 'EOF'
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=app/release.keystore
          EOF

      - name: Build release APK
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: flutter build apk --release --dart-define=APP_PACKAGE_ID=de.meinterminplaner.app

      - name: Build release AAB
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: flutter build appbundle --release --dart-define=APP_PACKAGE_ID=de.meinterminplaner.app

      - name: Upload release APK
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: mein-terminplaner-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload release AAB
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: mein-terminplaner-release-aab
          path: build/app/outputs/bundle/release/app-release.aab 
