- name: Decode keystore

        run:

          mkdir -p android/app

          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore

      - name: Create key.properties

        run: |

          cat > android/key.properties << 'EOF'

          storePassword=${{ secrets.KEYSTORE_PASSWORD }}

          keyPassword=${{ secrets.KEY_PASSWORD }}

          keyAlias=${{ secrets.KEY_ALIAS }}

          storeFile=app/release.keystore

          EOF

      - name: Build release APK

        run: flutter build apk --release --dart-define=APP_PACKAGE_ID=de.meinterminplaner.app

      - name: Build release AAB

        run: flutter build appbundle --release --dart-define=APP_PACKAGE_ID=de.meinterminplaner.app

      - name: Upload release APK

        uses: actions/upload-artifact@v4

        with:

          name: mein-terminplaner-release-apk

          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload release AAB

        uses: actions/upload-artifact@v4

        with:

          name: mein-terminplaner-release-aab

          path: build/app/outputs/bundle/release/app-release.aab 
